### ISSUE TITLE
Read card from HCE

### ISSUE THREAD

**Issue by masuikvova** [devnied/EMV-NFC-Paycard-Enrollment#57]
Hi

Is it possible to read a card from another device that supports HCE and retrieve it cryptogram? 
Thanks :)

**Comment by rozzalia** [comment]
yes its posible but now you have found it out right... what software u
using to take nfc emv on a mobile phone... you have some good software to
snapp bank card and hotell card... i wil send you a ebook on how to do it
.... i dont have a finish apk made for it ... and not shure i can do it
now.. because cant sit long time on a laptop at the time.... but wil guide
u fore shure
just help me with some software iff u have and its done :D


tir. 7. apr. 2020 kl. 11:23 skrev Masyuk Volodymyr <notifications@github.com

**Comment by rozzalia** [comment]
How many  nfc Numbers are in a atm Card posible to buy and write. In norway
We only USE contact less visa

søn. 6. des. 2020 kl. 22:48 skrev Julien Millau <notifications@github.com>:
